### ISSUE TITLE
Speech-to-text

### ISSUE THREAD

**Issue by lena143** [ASWE-PDA/Personal-Digital-Agent#11]
As a user,
I want the agent to understand what I'm saying
so that the agent can work according to my statements.

Acceptance criteria:
- [x] API for speech-to-text has been selected
- [x] API can be called by an adapter module in the backend

**Comment by itsmiriam42** [comment]
used API: Flutter Package speech_to_text

note regarding acceptance criteria "API can be called by an adapter module in the backend": recording of voice will be handled internally, spoken text is available by just using the variable "lastWords" anywhere in the code.
