### ISSUE TITLE
Documentation setup

### ISSUE THREAD

**Issue by lena143** [ASWE-PDA/Personal-Digital-Agent#8]
As a developer, 
I want to have one central location where I can find all the documentation
so that I can look up all the information I need in an easy way.

Acceptance criteria:
- [x] The documentation location has been set up.
- [ ] A structure has been set up in the form of headlines.
- [ ] The documentation can contain text, links, pictures and diagrams.
- [ ] The documentation is linked in the readme.

**Comment by Daimon-M** [comment]
set up github pages
